start python new_semspso.py 0 
start python new_semspso.py 1 
start python new_semspso.py 2 
start python new_semspso.py 3 
start python new_semspso.py 4 
start python new_semspso.py 5 
start python new_semspso.py 6 
start python new_semspso.py 7 
start python new_semspso.py 8 
start python new_semspso.py 9